### ISSUE TITLE
Sequence Diagrams - Parser error

### ISSUE THREAD

**Issue by krish777** [judepayne/dictim#4]
Here are the steps to reproduce the error.

**Step 1:** Write a d2 file which contains shape as sequence diagram.  

[seq-diagrams.d2.txt](https://
![seqMacDictim](https://github.com/user-attachments/assets/b06304fa-14a6-4d49-be7e-81b95b9d541b)
github.com/user-attachments/files/16615406/seq-diagrams.d2.txt)

**Step 2:** Create a dictim file to define the styles. 
[sequenceTemplate.edn.txt](https://github.com/user-attachments/files/16615445/sequenceTemplate.edn.txt)

**Step 3:** Run the dictim command to generate the d2 file.

**Step 4:** Run the d2 command to generate the svg file.

Step 5: Open the SVG file, it will display parser error.

Please check out the attachments.

**Comment by krish777** [comment]
[seq-diagrams.d2.txt](https://github.com/user-attachments/files/16615519/seq-diagrams.d2.txt)

**Comment by judepayne** [comment]
The parse error is down to line 9 in your file. 

````
  #style.stroke-dash: 5
````

It errors on the '#' and is fine if you remove it.

Were you trying to comment out this line? Not sure that will work inside curly braces.

I will have a think about push the error all the way through to the output in command line usage.
In the Clojure repl, the error is much clearer:

````
Could not parse:   #style.stroke-dash: 5
````

**Comment by krish777** [comment]
Instead of deleting line 9, commented it out and wanted to try it out and see how it works, so that I can uncomment it latter whenever I want it back. 

When # is removed the error is gone but it is not producing sequence diagram. 

![out2](https://github.com/user-attachments/assets/d1062f4d-5a22-45f4-b64c-0c7a500d7063)
Please check it out.

**Comment by judepayne** [comment]
This has turned into 3 separate issues on one ticket. Please raise new issues, isolating each, and close this issue so that fixes can be referenced to explicit issues.

Issue 1: can't parse commented out attrs

Issue 2: Improve how error reporting of parse errors is reporting through command line tool (with example - see my note above).

Issue 3: can't parse and compile sequence diagram

Please break out steps required to replicate each issue to the smallest & simplest possible set. For example, you don't need to do a full command line -a cycle to replicate these. Better to describe with:

Issue 1: a -p operation

Issue 2: a -p operation

Issue 3: not sure where the issue occurs, so leave for you to find exactly.
If I parse the corrected file in the repl, I get:

````
({"shape" "sequence_diagram"}
 ["scorer" {"shape" "person"}]
 ["scorer.t" "->" "itemResponse.t" "getItem()"]
 ["scorer.t" "<-" "itemResponse.t" "item" {"style.stroke-dash" 5}]
 ["scorer.t" "->" "item.t1" "getRubric()"]
 ["scorer.t" "<-" "item.t1" "rubric" {"style.stroke-dash" 5}]
 ["scorer.t" "->" "essayRubric.t" "applyTo(essayResp)"]
 ["itemResponse" "->" "essayRubric.t.c"]
 ["essayRubric.t.c" "->" "concept.t" "match(essayResponse)"]
 ["scorer" "<-" "essayRubric.t" "score" {"style.stroke-dash" 5}]
 ["scorer.t" "->" "itemOutcome.t1" "new"]
 ["scorer.t" "->" "item.t2" "getNormalMinimum()"]
 ["scorer.t" "->" "item.t3" "getNormalMaximum()"]
 ["scorer.t" "->" "itemOutcome.t2" "setScore(score)"]
 ["scorer.t" "->" "itemOutcome.t3" "setFeedback(missingConcepts)"])
````

If I then compile this back to d2 (no template needed) I get..

````
shape: sequence_diagram
scorer: {shape: person}
scorer.t -> itemResponse.t: getItem()
scorer.t <- itemResponse.t: item {style.stroke-dash: 5}
scorer.t -> item.t1: getRubric()
scorer.t <- item.t1: rubric {style.stroke-dash: 5}
scorer.t -> essayRubric.t: applyTo(essayResp)
itemResponse -> essayRubric.t.c
essayRubric.t.c -> concept.t: match(essayResponse)
scorer <- essayRubric.t: score {style.stroke-dash: 5}
scorer.t -> itemOutcome.t1: new
scorer.t -> item.t2: getNormalMinimum()
scorer.t -> item.t3: getNormalMaximum()
scorer.t -> itemOutcome.t2: setScore(score)
scorer.t -> itemOutcome.t3: setFeedback(missingConcepts)
````

Which looks like valid d2 to me. Where exactly is it broken?

**Comment by judepayne** [comment]
along with the smallest possible reproducible bug, say what it *should* do - the desired behaviour

**Comment by krish777** [comment]
Good idea, let me create separate tickets and close out this one.

**Comment by judepayne** [comment]
re. Issue 2 - pass through of complete error messages through cmd line tool operations: I have investigated and this is a non-issue - works fine, so no need to raise an issue for it

**Comment by krish777** [comment]
re. Issue 3 - Please checkout https://github.com/judepayne/dictim/issues/9

re. Issue 1 - Ticket exists already, Please checkout https://github.com/judepayne/dictim/issues/8
