### ISSUE TITLE
Can't parse commented out attrs 

### ISSUE THREAD

**Issue by judepayne** [judepayne/dictim#8]
This d2:

````d2
scorer.t <- item.t1: rubric {
  #style.stroke-dash: 5
}
````

cannot be parsed (and throws an error).

When the `'#'` characters is removed, it can be parsed.

attrs should be allowed to be commented out since this is valid d2

**Comment by judepayne** [comment]
This will require changes to both the d2 compiler and parser. The dot compiler is a TBD.

dictim represents comments as vectors:

````Clojure
[:comment "I am a comment"]
````

This could be represented in dictim (in an atto-map) as:

1. `{:comment {:attr-that-is-commented-out val}, attr val ...}`

2. `{[:comment :attr-that-is-commented-out] val, attr val ...}`

Perhaps some other ways.

Need to that about the most natural representation, before committing to adding this since this is a minor use case

**Comment by judepayne** [comment]
Decided to add this to dictim using notation no. 1 above

**Comment by judepayne** [comment]
@krish777 complete
See 5724d82 & a85e883 commits.
Note that even though attrs may be commented out, they are still validated both during compilation and parsing. This is because attrs in dictim syntax live in a clojure map, which must have keys and values - so no freeform text allowed. i.e. it's a data format whereas d2 is a text format

**Comment by judepayne** [comment]
@krish777 please review this.
Not sure this is the right approach. Maybe it's better to parse commented out attrs as

````
{:comment "style.italic: true"}
````

i.e. just treat them as strings

**Comment by krish777** [comment]
@eddielao Per our discussion, Can you please test this one?

**Comment by judepayne** [comment]
Closing
